### PR TITLE
Parent-child joins and tensors for content recommendation

### PR DESCRIPTION
**Pull request by anagao**
Blogpost from stream-ranking requested by @jobergum and @kkraune. 

Waiting on approvals from Brittany and Rosalie.

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Review by kkraune — APPROVED** [review]
Great! Merge at will :-)

**Comment by jobergum** [comment]
I'm so excited about this!

**Comment by anagao** [comment]
Updated date to 2021-02-22. Got approvals. 
@kkraune I don't have permissions so please merge for me--thanks!

**Comment by kkraune** [comment]
Thanks! It it live and looking great at https://blog.vespa.ai/ :-)

**Pull request merged**
