### PR TITLE
Build a News recommendation app from python with Vespa: Part 1

### PR DESCRIPTION
**Pull request by thigm85**
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Review by kkraune — APPROVED** [review]
Great! Generally, I don't think we should use the scooter images, this is not the scooter (same goes for the other blog post). I suggest you find something generic or something that better fits the news search/recommendation theme

**Comment by thigm85** [comment]
> Great! Generally, I don't think we should use the scooter images, this is not the scooter (same goes for the other blog post). I suggest you find something generic or something that better fits the news search/recommendation theme

Ok. I will change the images. 

IMHO, I would embrace the scooter image, the same way Docker uses the shipping container as their logo. There is no way to dissociate the scooter from our name unless we change the name.

**Review by lesters — APPROVED** [review]
LGTM. Please do change the header image 👍

**Comment by kkraune** [comment]
great images! good to merge!

**Pull request merged**
