### PR TITLE
News tutorials - part 3

### PR DESCRIPTION
**Pull request by thigm85**
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by thigm85** [comment]
The link-check error refers to another blog post not included in this PR.

**Comment by kkraune** [comment]
Very well written post, no comments on the text :-)

Consider referring/linking to https://blog.vespa.ai/parent-child-joins-tensors-content-recommendation/ which is on the same subject, with less details and without the python bindings. It also has an illustration that visually explains the parent child data - you can consider something similar here, too, it is a bit text heavy. Maybe users should be hinted to read Aaron's post first, as it is lighter, then this post for the details.

The post should also link to https://docs.vespa.ai/en/parent-child.html, can easily inline in the text where parent child is first mentioned (we should also consider reverse-linking from the guides to blog posts in a "Further reading" section, I will look into this).

**Review by kkraune — APPROVED** [review]

**Comment by thigm85** [comment]
> Very well written post, no comments on the text :-)
> 
> Consider referring/linking to https://blog.vespa.ai/parent-child-joins-tensors-content-recommendation/ which is on the same subject, with less details and without the python bindings. It also has an illustration that visually explains the parent child data - you can consider something similar here, too, it is a bit text heavy. Maybe users should be hinted to read Aaron's post first, as it is lighter, then this post for the details.
> 
> The post should also link to https://docs.vespa.ai/en/parent-child.html, can easily inline in the text where parent child is first mentioned (we should also consider reverse-linking from the guides to blog posts in a "Further reading" section, I will look into this).

@kkraune There is a link to https://blog.vespa.ai/parent-child-joins-tensors-content-recommendation/ at the end of the first paragraph. I will add https://docs.vespa.ai/en/parent-child.html. 

Reverse linking would be great.

**Review by lesters — APPROVED** [review]
Great!

**Pull request merged**
