### PR TITLE
Add post on evaluation uncertainty

### PR DESCRIPTION
**Pull request by thigm85**
@kkraune I am opening this PR, but maybe we should address [VESPA-24547](https://jira.ouryahoo.com/browse/VESPA-24547) first? I have added some examples and comparisons in the JIRA ticket.

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by kkraune** [comment]
I added the first HTML dump you have me, it worked well with a few minor fixes. Also made minimal changes to css/templates. I will send for approval based on this, but we might want to fine-tune it a little

**Comment by thigm85** [comment]
@kkraune Updated the post given the latest `learntorank` changes

**Review by kkraune — APPROVED** [review]
👍  great post!

**Comment by thigm85** [comment]
> 👍 great post!

Should I merge?

**Pull request merged**
