### PR TITLE
Write post that announces the IN query operator.

### PR DESCRIPTION
**Pull request by geirst**
@jobergum please review

### CODE REVIEW

**Review by jobergum — APPROVED** [review]

**Comment by jobergum** [comment]
Sweet and short - congratulations!

**Comment by geirst** [comment]
@jobergum PTAL

**Comment by jobergum** [comment]
Great, I would assume that this is single-threaded so I would add that, otherwise 👍

**Comment by geirst** [comment]
> Great, I would assume that this is single-threaded so I would add that, otherwise 👍

Good point, added.

**Comment by geirst** [comment]
@bratseth FYI

**Pull request merged**
