### PR TITLE
Draft private endpoints blog

### PR DESCRIPTION
**Pull request by jonmv**
@oyving please review.

### CODE REVIEW

**Comment by jonmv** [comment]
@kkraune if you want to have a quick look as well.

**Comment by oyving** [comment]
LGTM! Short and sweet 😄

**Comment by kkraune** [comment]
I'll take a look now

**Review by kkraune — APPROVED** [review]
nice! a few edits to make images load

**Comment by jonmv** [comment]
Great, thanks, both of you!

**Pull request merged**
