### PR TITLE
Blog post announcing maximum inner product search.

### PR DESCRIPTION
**Pull request by geirst**
@kkraune and @arnej27959 please review
@bratseth FYI

### CODE REVIEW

**Review by kkraune — APPROVED** [review]
great! I assume the same content as in the doc I reviewed yesterday :-)

**Comment by geirst** [comment]
> great! I assume the same content as in the doc I reviewed yesterday :-)

Yes, that is correct.

**Review by geirst — COMMENTED** [review]
👍

**Review by arnej27959 — APPROVED** [review]
this looks very good to me

**Pull request merged**
